<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('PPC'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
       <!-- <?php 
		echo  $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') 
		?>-->

<?php 
		echo  $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
						->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
					    ->prependStylesheet($this->basePath() . '/css/style.css')
						->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') 
						->appendStylesheet($this->basePath() . '/css/font-awesome/css/font-awesome.min.css') 

		?>

	<!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
	<!--[if lt IE 9]>
	<script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->
	<script>
       var baseUrl  = '<?php echo  $this->url('home');?>';
       var adminUrl = '<?php echo  $this->url('admin');?>';
    </script>	
    <?php echo $this->headScript()->appendFile($this->basePath() . '/js/html5.js','text/javascript',array('conditional' => 'lt IE 9')) 
								  ->appendFile($this->basePath() . '/js/jQuery/jquery-1.9.1.min.js') 
								  ->appendFile($this->basePath() . '/js/bootstrap.min.js') 
								  ->appendFile($this->basePath() . '/js/highcharts/highcharts.js') 
								  ->appendFile($this->basePath() . '/js/curvy.corners.trunk.js') 

    ?>

                                      

    </head>
    <body>
    <div class="container">

            <div class="header">
                <h1><a href="#">Jimmy Data</a></h1>
                
			<?php 
                 
                   if($this->zfcUserIdentity()):
                         if($this->zfcUserIdentity()->getType()=='admin'):
                            echo $this->navigation('adminnavigation')->menu() 
																	  ->setPartial('partial/menu.phtml')
																	  ->render();
                         endif; 
                   endif;
                   ?>
                
              
              
              
                
 			 <?php if($this->zfcUserIdentity()):?>
                <div class="usersetting">
                    <div class="user nav ">
                        <?php echo $this->gravatar($this->zfcUserIdentity()->getEmail(),array('img_size'=>20)) ?>
                        <p><a href="#"> Hello, <?php echo $this->zfcUserDisplayName() ?></a></p>
                    </div>
                    <a   title="Logout" href="<?php echo $this->url('user/logout') ?>" class="logout"></a>

                </div>
              <?php endif;?>  
                
            </div><!--/Header-->
   		<div id="alert-container">
         <?php $this->flashMessages();?>  
		</div>
    	<?php 
		  if($this->url()=='/dashboard'):
		?>
            <div class="wrpr radius5">
				<?php echo $this->content; ?>
         	</div> 
         <?php
		  else:
		 	echo $this->content;
		  endif;
         ?>
         
        <?php echo $this->inlineScript() ?>
    </body>
</html>
