<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Eway\Module'                           => __DIR__ . '/Module.php',
  'Eway\Service\EwaySoapApi'              => __DIR__ . '/src/Eway/Service/EwaySoapApi.php',
  'Eway\Service\Factory\RecurringFactory' => __DIR__ . '/src/Eway/Service/Factory/RecurringFactory.php',
  'Eway\Service\Recurring'                => __DIR__ . '/src/Eway/Service/Recurring.php',
);
