<div class="row-fluid">
   <p><h4>Hi Admin </h4></p>            
   <p><?php echo $user->getName();?> has sent a  Custom Quote Request</p>
   <p>
      <p><strong>Reports Required</strong> :<?php echo $support['no_reports_required']?></p>
      <p><strong>Clients Managing</strong> :<?php echo $support['no_clients_managing']?></p>
      <p><strong>Alternate Email</strong> :<?php echo $support['alternate_email']?></p>
      <p><strong>Message</strong><br /><br /><?php echo $support['message']?></p>
   </p>
</div>