<div class="row-fluid">
   
   <p>
    <h4>Dear, <?php if(isset($rawUserData['firstname'])) echo $rawUserData['firstname'].' '.$rawUserData['lastname']; else echo $user->getName();?></h4></p>     
    <p>
        This is a payment receipt for Invoice #<?php echo $paymentResponse->trans_id;?> sent on <?php echo date('d/m/Y'); ?>
    </p>
    <p>
        <strong>Invoice</strong> #<?php echo $paymentResponse->trans_id;?> $<?php echo $paymentResponse->amount; ?> <?php echo $currency;?><br />
        <strong>Total</strong>: $<?php echo $paymentResponse->amount; ?> <?php echo $currency;?><br />
        <strong>Included</strong> GST: $10.00 AUD<br />
    </p>
    
<!--    
    <strong>Transaction</strong> #: XXXXXXXXX
-->   
    <p> 
        The GST component is one eleventh of $<?php echo $paymentResponse->amount?> <?php echo $currency;?>
    </p>
    <p>
        You may review your invoice history at any time by logging in to your client area.
    </p>
    <p>
        Note: This email will serve as an official receipt for this payment.
    </p>
</div>