<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('PPC'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php 
		echo  $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') 
						//->appendStylesheet('//netdna.bootstrapcdn.com/font-awesome/2.0/css/font-awesome.css')
						//->prependStylesheet('http://fonts.googleapis.com/css?family=Autour+One')
						//->prependStylesheet($this->basePath() . '/css/fonts.css')
						->appendStylesheet('http://fonts.googleapis.com/css?family=Berkshire+Swash|Permanent+Marker|Leckerli+One|Open+Sans:400,700,300')
		?>
     <!--[if IE 7]>
      <link rel="stylesheet" type="text/css"  href="<?php echo $this->basePath().'/fonts/fontawesome/css/font-awesome-ie7.css'; ?>">
     <![endif]-->

	<!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
	<!--[if lt IE 9]>
	<script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->

    <?php echo $this->headScript()->appendFile($this->basePath() . '/js/html5.js','text/javascript',array('conditional' => 'lt IE 9')) 
								  ->appendFile($this->basePath() . '/js/bootstrap.min.js') 
    ?>

                                      

    </head>
    <body>
        <div class="container">
             
			<?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2012 by Webmarketers Pty Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
    </body>
</html>
