<div class="row-fluid">
   <div attr="desc">
     <div>
       <p>Hi I'm Jimmy,</p>
       <p><strong><?php if($agency->getName()) echo $agency->getName(); else echo $agency->getEmail();?></strong> wants to share a report with you.</p>
       <p>To access your new reporting dashboard you can login using the following details:</p>
       <p><a href="http://reports.jimmydata.com/" target="_blank">reports.jimmydata.com</a><br /></p>
       <p>
         	Username/Email: <?php echo $user->getEmail(); ?><br />
         	Password: <?php echo $rawUserData['password']?>
       </p>
      <p>The report you will be viewing will be real time data. Remember you can also change the date range if you want to view your data in another timeframe.</p>
      <p>Love using Jimmy to view your reports? Then why go backwards? Get your Agency to use Jimmy and access all your real time data in the one place!</p>
     </div>
   </div>
   <div>
   <div>
   <br />
    
</div>