<div class="row-fluid">
   
   <p><h4>Hi, <?php echo $rawUserData['firstname']?></h4></p>            
   
   <p><h4>Good to see you are making the most out of Jimmy!</h4></p>

   <p>
   	You may already be aware, but to access your report simply visit this link <insert url> then just login with Google and authorise Jimmy to get started.
   </p>

    <p><strong>What is in my subscription?</strong></p>
    <p>
        Your current subscription allows you to use <No. of> templates.
        Again, If your find yourself running out of templates you can upgrade anytime.
    </p>
    
	<p>(TBC) For more info about Jimmy you can checkout the following posts on Jimmy's blog.</p>
	
    <p>Cool things Jimmy can do</p>
	
    <ul>
    	<li>Sharing a Jimmy report</li>
		<li>Teach</li>
    </ul>
 </div>