<div class="row-fluid">
   
   <p><h4>Hi, <?php echo $rawUserData['firstname']?></h4></p>            
   
   <p> 
   	<h4>Thanks for signing up with Jimmy!</h4>  
   </p>
   	<p>To get started simply visit this link <a href="https://app.jimmydata.com">http://app.jimmydata.com</a> then just login with Google and authorise Jimmy to get started.</p>
	<p><strong>What is in my subscription?</strong></p>
    <p>
      Your current subscription allows you to use <No. of> templates.
      If your find yourself running out of templates you can upgrade anytime.
    </p>
    
    <p>(TBC) For more info about Jimmy you can checkout the following posts on Jimmy's blog.</p>
    <p><strong>Cool things Jimmy can do</strong></p>
	
    <ul>
    	<li>Sharing a Jimmy report</li>
		<li>Teach Jimmy</li>
	</ul>
    
</div>