<div class="row-fluid">
   
   <p><h4>Hi, <?php echo $user->getName();?></h4></p>            
   
   <p><h4>Thanks for giving Jimmy a shot as your reporting guru.</h4></p>
   <p>To get started simply visit  <a href="https://app.jimmydata.com" target="_blank">https://app.jimmydata.com</a> then just login with Google and authorise Jimmy to get started.</p>
   <p><strong>What do you get in your trial?</strong></p>

    <p>Jimmy's Free Trial allows you 1 template to edit. You can still use all of Jimmy's cool features and when you are ready, you can hire him full time by upgrading to one of our other packages.</p>

	<p>(TBC) For more info about Jimmy you can checkout the following posts on Jimmy's blog.</p>
	
    <p><strong>Cool things Jimmy can do</strong></p>
	
    <ul>
    	<li>Sharing a Jimmy report</li>
		<li>Teach Jimmy</li>
	</ul>
    
</div>