<?php
 $kpi = $this->kpi;
 $kpiDataTotalCompare = $this->kpiDataTotalCompare;
 $kpiDataSegmented    = $this->kpiDataSegmented;
 $key = $this->key;
 ?>
 <div class="panel panel-danger red panel-red" style="background:#F33751 !important;">

    <div class="panel-heading">
            <?php echo $kpi['caption'];?>
    </div>

    <div class="panel-body" style="background:#F33751 !important;">
        <div class="content-box-wrapper"  style="width: 120px;height:100px;margin: 0px auto;  border:none !important; background:#F33751 !important; display:table;">
                 <figure style="width: 140px; height: 108px;background:#F33751;"  class="jimmy-chart-kpi"  data-graphdata='<?php echo json_encode($kpiDataSegmented[$kpi['key']]);?>' data-typeg="line" ></figure>
        </div>
    </div>
                                        <div class="kpi-dash-line">&nbsp;</div>

    <div class="panel-footer">
        <?php if(!is_null($kpiDataTotalCompare[$key]['rawValue'])):?>
            <table class="table table-bordered table-footer"  style="background-color: #F33751 !important; color:#fff !important;">
                <thead>
                    <tr>
                        <th colspan="3"><span class="font-size-10 font-roboto" style="color:#fff; background-color: #F33751 !important; "><?php echo $kpi['sub_caption'];?></span></th>
                    </tr>
                    <tr>
                        <?php if(!is_null($kpiDataTotalCompare[$key]['value'])):?>
                            <th class="font-roboto font-size-10" style="color:#fff !important; background-color: #F33751 !important; " >Previous</th>
                        <?php endif;?>
                        <th style="text-align:center;color:#fff !important; background-color: #F33751 !important;" class="font-roboto font-size-10"  >Current</th>
                        <th style="text-align:left;color:#fff !important; background-color: #F33751 !important;"></th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <?php if(!is_null($kpiDataTotalCompare[$key]['value'])):?>
                        <td>
                            <b>
                                <small class="font-size-10 font-gray-dark font-roboto"  style="color:#fff !important; background-color: #F33751 !important;" ><?php echo $kpiDataTotalCompare[$key]['value'];?></small>
                            </b>
                        </td>
                        <?php endif;?>
                        <td>
                            <b>
                                <span class="font-size-10 font-gray-dark font-roboto" style="color:#fff !important; background-color: #F33751 !important;" ><small ><?php echo $kpi['value'];?></small></span>
                            </b>
                        </td>
                        <td>
                            <b>
                             <?php if(!is_null($kpiDataTotalCompare[$key]['rawValue'])):?>
                                <small class="font-size-10 font-gray-dark font-roboto" style="color:#fff !important; background-color: #F33751 !important;" >
                                    <?php echo $this->metrics()->calcComparedMetrics($kpi['value'],$kpiDataTotalCompare[$key]['value'])?>
                                </small>
                             <?php endif;?>
                            </b>
                        </td>
                    </tr>
                </tbody>
            </table>
         <?php else:?>
            <table class="table table-bordered table-footer"  style="background-color: #F33751 !important;color:#fff !important; background-color: #F33751 !important;">
                <thead>
                    <tr>
                        <th style="text-align:center; background-color: #F33751 !important;" class="font-roboto"><span class="font-size-10" style="color:#fff !important; background-color: #F33751 !important;" ><?php echo $kpi['sub_caption'];?></span></th>
                    </tr>
                </thead>
                <tbody>
                <tr>
                    <td style="text-align:center; background-color: #F33751 !important;" class="font-roboto">
                            <small class="kpi-caption" style="color:#fff !important; background-color: #F33751 !important;" ><?php echo $kpi['value'];?></small>
                    </td>
                </tr>
                </tbody>
            </table>
          <?php endif;?>
    </div>
</div>