<?php
$form = $this->registerForm;
$form->prepare();
$form->setAttribute('action', $this->url('admin/client/add'));
$form->setAttribute('method', 'post');
$form->setAttribute('class', 'form-horizontal');
?>
  <form class="form-horizontal" method="post" name="client_form" action="/admin/client/add">  
                 <fieldset>  
				  <legend>Create Report</legend>  
                  <div class="control-group">  
					<?php echo $this->formLabel($element->setLabelAttributes(array('class'=>'control-label'))) ?>
                    <div class="controls">  
			 		<?php echo $this->formInput($element) . $this->formElementErrors($element) ?>                   
                      <p class="help-block">Customer's Full Name.</p>  
                    </div>  
                  </div>  
                  <div class="control-group">  
                    <label class="control-label" for="email" name='email'>Client Email</label>  
                    <div class="controls">  
                      <input type="text" class="input-xlarge" name="email" id="email">  <?php echo  $this->formElementErrors($form->get('email')) ?>
                      <p class="help-block">Customer's email registered in Adwords.</p>  
                    </div>  
                  </div>  
                  <div class="control-group">  
                    <label class="control-label" for="adwords_client_id">Adwords Client Id</label>  
                    <div class="controls">  
                      <input type="text" class="input-xlarge" id="adwords_client_id" name="adwords_client_id"> <?php echo  $this->formElementErrors($form->get('adwords_client_id')) ?> 
                      <p class="help-block">Customer's Id as shown in Adwords</p>  
                    </div>  
                  </div>  
                  <div class="form-actions">  
                    <button type="submit" class="btn btn-primary" id="save">Save changes</button>  
                    <button class="btn">Cancel</button>  
                  </div>  
                    <?php if ($this->redirect): ?>
        <input type="hidden" name="redirect" value="<?php echo $this->redirect ?>" />
    <?php endif ?>
                </fieldset>  
        </form>  
                   
 