  <?php  if($this->clients->count()):?>
        <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered table-hover " id="example">
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Email</th>
                <th>Adwords Client Id</th>
                <th>Status</th>
            </tr>
        </thead>
       
        <tbody>
         <?php foreach($this->clients as $client):  //echo '<pre>';print_r($client);?>
            <tr class="odd gradeX" onclick="location.href='<?php echo $this->url('admin/client/view').'/'.$client->getId();?>'">
                <td><?php echo $client->getId();?></td>
                <td><?php echo $client->getName();?></td>
                <td><?php echo $client->getEmail();?></td>
                <td><?php echo $client->getAdwordsClientId();?></td>
                <td><?php echo $client->getState()?'Active':'Inactive';?></td>
                
            </tr>
         <?php endforeach;?>
         </tbody>
        
        </table>      
<?php  else: ?>

<div class="alert alert-error">
 No Clients.
</div>
<?php endif;  ?>  
