<?php 

 if($this->reportList): ?>
    <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered table-hover" id="example">
    <thead>
		<tr>
			<th>ID</th>
			<th>Title</th>
			<th>Report Type</th>
			<th>Metrics Type</th>
			<th>Metrics</th>
			<th>Date Range</th>
			<th>Compare?</th>
			<th>Created</th>
			<th>Actions</th>
		</tr>
	</thead>
   
    <tbody>
     <?php foreach($this->reportList as $report):?>
		<tr class="odd gradeX" onclick="location.href='<?php echo $this->url('admin/client/viewreport').'/'.$report->getId();?>';">
			<td><?php echo $report->getId();?></td>
			<td><?php echo $report->getTitle();?></td>
			<td><?php echo $metrics_service->getReportType($report->getReportType());?></td>
			<td><?php echo $metrics_service->getMetricsType($report->getMetricsType());?></td>
        	<td><?php echo $metrics_service->getMetrics($report->getMetricsType(),$report->getMetrics());?></td>
        	<td><?php echo $metrics_service->getDateRange($report->getDateRange());?></td>
        	<td><?php echo $report->getCompare()?'Yes':'No';?></td>
			<?php 
			/*
			$raw_data =  $report->getRawData();
			$raw_data_string = '';
			if($raw_data){
				$raw_data_explode = @explode(',',$raw_data);	
				if(is_array($raw_data_explode)){
					foreach($raw_data_explode as $key => $val){
						if($key < 2 ){ 
					 		$raw_data_array[] = $metrics_service->getMetrics(1,$val);
						} else {
							$raw_data_array[] = '...';
							break;
						}
					}
				    
					$raw_data_string = implode(',',$raw_data_array);	 
				}
			}
			
			echo $raw_data_string?$raw_data_string:'-';*/
			?>
			<td><?php echo date('d M Y',mktime(strtotime($report->getDateAdded())));?></td>
            <td><a href="<?php echo $this->url('admin/client/editreport').'/'.$report->getId();?>">Change</a></td>
		</tr>
     <?php endforeach;?>
     </tbody>
    
    </table>      
<?php  else: ?>

<div class="alert alert-error">
 Sorry! No Reports for this client.
</div>
<?php endif;  ?>  
