<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Admin\Module'                                            => __DIR__ . '/Module.php',
  'Admin\Authentication\Adapter\AbstractAdapter'            => __DIR__ . '/src/Admin/Authentication/Adapter/AbstractAdapter.php',
  'Admin\Authentication\Adapter\AdapterChain'               => __DIR__ . '/src/Admin/Authentication/Adapter/AdapterChain.php',
  'Admin\Authentication\Adapter\AdapterChainEvent'          => __DIR__ . '/src/Admin/Authentication/Adapter/AdapterChainEvent.php',
  'Admin\Authentication\Adapter\AdapterChainServiceFactory' => __DIR__ . '/src/Admin/Authentication/Adapter/AdapterChainServiceFactory.php',
  'Admin\Authentication\Adapter\ChainableAdapter'           => __DIR__ . '/src/Admin/Authentication/Adapter/ChainableAdapter.php',
  'Admin\Authentication\Adapter\Db'                         => __DIR__ . '/src/Admin/Authentication/Adapter/Db.php',
  'Admin\Authentication\Storage\Db'                         => __DIR__ . '/src/Admin/Authentication/Storage/Db.php',
  'Admin\Controller\AdminController'                        => __DIR__ . '/src/Admin/Controller/AdminController.php',
  'Admin\Controller\AgencyController'                       => __DIR__ . '/src/Admin/Controller/AgencyController.php',
  'Admin\Controller\ClientController'                       => __DIR__ . '/src/Admin/Controller/ClientController.php',
  'Admin\Controller\Plugin\AdminUserAuthentication'         => __DIR__ . '/src/Admin/Controller/Plugin/AdminUserAuthentication.php',
  'Admin\Controller\SettingsController'                     => __DIR__ . '/src/Admin/Controller/SettingsController.php',
  'Admin\Controller\UserController'                         => __DIR__ . '/src/Admin/Controller/UserController.php',
  'Admin\Mapper\AdminUser'                                  => __DIR__ . '/src/Admin/Mapper/AdminUser.php',
  'Admin\Mapper\AdminUserHydrator'                          => __DIR__ . '/src/Admin/Mapper/AdminUserHydrator.php',
  'Admin\Navigation\AdminNavigationFactory'                 => __DIR__ . '/src/Admin/Navigation/AdminNavigationFactory.php',
  'Admin\View\Helper\HasAdminUserIdentity'                  => __DIR__ . '/src/Admin/View/Helper/HasAdminUserIdentity.php',
  'Admin\View\Helper\UserDisplayName'                       => __DIR__ . '/src/Admin/View/Helper/UserDisplayName.php',
);
