<?php
// Generated by Zend Framework 2
return array(
    'Chat\Module'                               => __DIR__ . '/Module.php',
    'Chat\Controller\MessageApiController'      => __DIR__ . '/src/Chat/Controller/MessageApiController.php',
    'Chat\Entity\Message'                       => __DIR__ . '/src/Chat/Entity/Message.php',
    'Chat\Entity\MessageInterface'              => __DIR__ . '/src/Chat/Entity/MessageInterface.php',
    'Chat\Mapper\Message'                       => __DIR__ . '/src/Chat/Mapper/Message.php',
    'Chat\Mapper\MessageHydrator'               => __DIR__ . '/src/Chat/Mapper/MessageHydrator.php',
    'Chat\Mapper\MessageInterface'              => __DIR__ . '/src/Chat/Mapper/MessageInterface.php',
    'Chat\Service\Message'                      => __DIR__ . '/src/Chat/Service/Message.php',
    'ChatTest\Bootstrap'                        => __DIR__ . '/test/Bootstrap.php',
    'ChatTest\Controller\MessageControllerTest' => __DIR__ . '/test/ChatTest/Controller/MessageControllerTest.php',
);