<div id="page-title"  ng-style="!showSearch?{padding:'5px'}:null">
    <div id="breadcrumb-right" ng-if="showSearch" style="height:35px;position:relative;padding-top: 18px;padding-right: 20px; ">
        <div id="sidebar-search" filter="#content-view">
            <input  type="text" placeholder="Search..." class="input tooltip-button" data-placement="bottom"  id="" name="">
            <i class="glyph-icon icon-search"></i>
        </div>
    </div>
    <div id="progress-bar" progress-bar style="padding:10px;display: none" >{{message}}</div>
    <flash-message></flash-message>
</div>

<ng-include src="'/src/app/dashboard/support.html'" ></ng-include>
<div id="content-view" ng-view></div>