<div class="hero-unit">
    
    <div class="row-fluid">
		<div class="span6">
			<header class="jumbotron masthead">
				<div class="inner">
                    <h1  class="welcome"><?php echo sprintf($this->translate('Welcome to %sPPC %s'), '<span class="zf-green">', '</span>') ?></h1>
					<p>PPC is a simple app for reporting adwords campaign.</p>
				</div>
			</header>

			<div id="home-big-signin">
				<div class="buttons">
				</div>
			</div>
		</div>
        
        
		<div class="span6">
			<div class="row-fluid">

		<?php       echo $this->userLogin;      ?>

			</div>
		</div>
        
        
	</div>

</div>

