<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Application\Module'                                    => __DIR__ . '/Module.php',
  'Application\Authentication\Adapter\HybridAuth'         => __DIR__ . '/src/Application/Authentication/Adapter/HybridAuth.php',
  'Application\Controller\ClientController'               => __DIR__ . '/src/Application/Controller/ClientController.php',
  'Application\Controller\CoworkerApiController'          => __DIR__ . '/src/Application/Controller/CoworkerApiController.php',
  'Application\Controller\DashboardApiController'         => __DIR__ . '/src/Application/Controller/DashboardApiController.php',
  'Application\Controller\DashboardController'            => __DIR__ . '/src/Application/Controller/DashboardController.php',
  'Application\Controller\Factory\IndexControllerFactory' => __DIR__ . '/src/Application/Controller/Factory/IndexControllerFactory.php',
  'Application\Controller\IndexController'                => __DIR__ . '/src/Application/Controller/IndexController.php',
  'Application\Controller\PackageApiController'           => __DIR__ . '/src/Application/Controller/PackageApiController.php',
  'Application\Controller\PaymentApiController'           => __DIR__ . '/src/Application/Controller/PaymentApiController.php',
  'Application\Controller\Plugin\UserAuthentication'      => __DIR__ . '/src/Application/Controller/Plugin/UserAuthentication.php',
  'Application\Controller\UserController'                 => __DIR__ . '/src/Application/Controller/UserController.php',
  'Application\Service\HybridAuthAdapterFactory'          => __DIR__ . '/src/Application/Service/HybridAuthAdapterFactory.php',
  'Application\Service\UserControllerFactory'             => __DIR__ . '/src/Application/Service/UserControllerFactory.php',
  'Application\View\Helper\HasUserIdentity'               => __DIR__ . '/src/Application/View/Helper/HasUserIdentity.php',
  'Application\View\Helper\LoginWidget'                   => __DIR__ . '/src/Application/View/Helper/LoginWidget.php',
  'Application\View\Helper\SocialSignInButton'            => __DIR__ . '/src/Application/View/Helper/SocialSignInButton.php',
  'Application\View\Helper\UserIdentity'                  => __DIR__ . '/src/Application/View/Helper/ZfcUserIdentity.php',
);
