<?php
// Generated by ZF2's ./bin/templatemap_generator.php
/*return array(
    'application/dashboard/agency'    => __DIR__ . '/view/application/dashboard/agency.phtml',
    'application/dashboard/authorize' => __DIR__ . '/view/application/dashboard/authorize.phtml',
    'application/dashboard/user'      => __DIR__ . '/view/application/dashboard/user.phtml',
    'application/index/account'       => __DIR__ . '/view/application/index/account.phtml',
    'application/index/changepwd'     => __DIR__ . '/view/application/index/changepwd.phtml',
    'application/index/edit'          => __DIR__ . '/view/application/index/edit.phtml',
    'application/index/index'         => __DIR__ . '/view/application/index/index.phtml',
    'application/index/profile'       => __DIR__ . '/view/application/index/profile.phtml',
    'application/user/account'        => __DIR__ . '/view/application/user/account.phtml',
    'application/user/changepwd'      => __DIR__ . '/view/application/user/changepwd.phtml',
    'application/user/edit'           => __DIR__ . '/view/application/user/edit.phtml',
    'error/404'                       => __DIR__ . '/view/error/404.phtml',
    'error/index'                     => __DIR__ . '/view/error/index.phtml',
    'layout/layout-login'             => __DIR__ . '/view/layout/layout-login.phtml',
    'layout/layout'                   => __DIR__ . '/view/layout/layout.phtml',
    'partial/menu'                    => __DIR__ . '/view/partial/menu.phtml',
    'scn-social-auth/user/login'      => __DIR__ . '/view/scn-social-auth/user/login.phtml',
    'scn-social-auth/user/register'   => __DIR__ . '/view/scn-social-auth/user/register.phtml',
    'zfc-user/user/index'             => __DIR__ . '/view/zfc-user/user/index.phtml',
    'zfc-user/user/login'             => __DIR__ . '/view/zfc-user/user/login.phtml',
);
*/