<?php echo $this->doctype(); ?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Jimmy'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

		<?php
		echo  $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.png'))
						->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
            ->prependStylesheet($this->basePath() . '/css/dashboard.css')
            ->prependStylesheet($this->basePath() . '/css/style-pdf.css')
						->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
						->appendStylesheet($this->basePath() . '/css/font-awesome/css/font-awesome.min.css')

		?>

	<!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
	<!--[if lt IE 9]>
		<script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->

    <?php echo $this->headScript()->appendFile($this->basePath() . '/js/html5.js','text/javascript',array('conditional' => 'lt IE 9'))
								  ->appendFile($this->basePath() . '/js/jQuery/jquery-1.9.1.min.js')
								  ->appendFile($this->basePath() . '/js/curvy.corners.trunk.js')
                  ->appendFile($this->basePath() . 'assets/js/plugins/easypiechart/easypiechart.js')
                  ->appendFile($this->basePath() . 'assets/js/plugins/sparkline/jquery.sparkline.min.js')
                  ->appendFile($this->basePath() . 'assets/js/plugins/dropzone/dropzone.js')
                  ->appendFile($this->basePath() . 'assets/js/plugins/chartJs/Chart.min.js')
                  ->appendFile($this->basePath() . 'assets/js/plugins/jsKnob/jquery.knob.js')
                  ->appendFile($this->basePath() . 'assets/js/jquery.easy-pie-chart/dist/angular.easypiechart.min.js')



    ?>



    </head>
    <body>


    <div class="container">
         <div class="header">
            <h1><a href="<?php echo $this->url('home') ?>">Jimmy Data</a></h1>
        </div><!--/Header-->

         <?php
    	 	echo $this->content;
         ?>

        <?php echo $this->inlineScript() ?>
    </div>
        <!-- Google Tag Manager -->
        <noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-MKF6R5"
        height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
        <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
        new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
        j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
        '//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
        })(window,document,'script','dataLayer','GTM-MKF6R5');</script>
        <!-- End Google Tag Manager -->

    </body>

</html>
