<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate($this->title?$this->title:'Jimmy'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php
        $fav_icon = $this->logo_config['favicon']?$this->logo_config['favicon']:'favicon.png';
        echo  $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/'.$fav_icon))
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
		?>
     <!--[if IE 7]>
      <link rel="stylesheet" type="text/css"  href="<?php echo $this->basePath().'/fonts/fontawesome/css/font-awesome-ie7.css'; ?>">
     <![endif]-->

	<!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
	<!--[if lt IE 9]>
	<script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->


    <?php echo $this->headScript()->appendFile($this->basePath() . '/js/html5.js','text/javascript',array('conditional' => 'lt IE 9'))
								  ->appendFile($this->basePath() . '/js/jQuery/jquery-1.9.1.min.js')
								  ->appendFile($this->basePath() . '/js/bootstrap.min.js')
								  ->appendFile($this->basePath() . '/js/curvy.corners.trunk.js')
								  ->appendFile($this->basePath() . '/js/application.js')
    ?>



    </head>
    <body class="logBdy">
        <?php echo $this->content; ?>
        <!-- Google Tag Manager -->
        <noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-MKF6R5"
        height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
        <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
        new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
        j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
        '//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
        })(window,document,'script','dataLayer','GTM-MKF6R5');</script>
        <!-- End Google Tag Manager -->
    </body>
</html>
