  <?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <?php echo $this->headTitle($this->translate('Jimmy'))->setSeparator(' - ')->setAutoEscape(false) ?>
        <meta name="description" content="">
        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no') ?>

        <!-- Favicons -->

        <link rel="apple-touch-icon-precomposed" sizes="144x144" href="assets/images/icons/apple-touch-icon-144-precomposed.png">
        <link rel="apple-touch-icon-precomposed" sizes="114x114" href="assets/images/icons/apple-touch-icon-114-precomposed.png">
        <link rel="apple-touch-icon-precomposed" sizes="72x72"   href="assets/images/icons/apple-touch-icon-72-precomposed.png">
        <link rel="apple-touch-icon-precomposed" href="assets/images/icons/apple-touch-icon-57-precomposed.png">
        <link rel="shortcut icon" href="/images/favicon.png">

		<?php
		echo  $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.png'))
			      ->appendStylesheet($this->basePath()  . '/assets/css/minified/aui-production.min.css')
            ->appendStylesheet($this->basePath()  . '/assets/themes/minified/fides/color-schemes/dark-blue.min.css')
            ->appendStylesheet($this->basePath()  . '/assets/themes/minified/fides/common.min.css')
            ->appendStylesheet($this->basePath()  . '/assets/themes/minified/fides/animations.min.css')
            ->appendStylesheet($this->basePath()  . '/assets/themes/minified/fides/responsive.min.css')
            ->appendStylesheet($this->basePath()  . '/css/dashboard.css')
		?>




    <?php echo $this->headScript()->appendFile($this->basePath() . '/js/html5.js','text/javascript',array('conditional' => 'lt IE 9'))
				          ->appendFile($this->basePath() . '/js/jQuery/jquery-1.9.1.min.js')
                  ->appendFile('https://ajax.googleapis.com/ajax/libs/angularjs/1.2.14/angular.min.js')
                  ->appendFile('https://ajax.googleapis.com/ajax/libs/angularjs/1.2.14/angular-route.min.js')
                  ->appendFile('https://ajax.googleapis.com/ajax/libs/angularjs/1.2.14/angular-resource.min.js')
                  ->appendFile($this->basePath() . '/js/dirPagination.js')
                  ->appendFile($this->basePath() . '/src/app/loading.js')
                  ->appendFile($this->basePath() . 'assets/js/jquery.easy-pie-chart/dist/angular.easypiechart.min.js')
                  ->appendFile($this->basePath() . '/src/app/dashboard.js')

    ?>
    </head>

    <body ng-app="Jimmy.dashboard" >
      <div id="page-content-wrapper">
        <?php echo $this->content; ?>
      </div>
    </body>
</html>
