<div class="layout float-left">
 
  <div class="poster" style="padding-top:100px">
      <p>Welcome <b style="font-size:25px">Warrior Forum</b> member.<br/> <br/> 
      To take advantage of your Warrior Special Offer simply sign up to JimmyData by signing in with your Google Account below. <br/><br/>You will then automatically be upgraded to our starter package!</p>
    </div>
</div>

<div class="layout float-left">
  <div class="poster-white float-left">
      <div class="poster-white-inner">
          <div class="logo-button float-left"><a href="#"><img src="/images/logo3.jpg" alt="" /></a></div>
            <div class="google-button float-left">
              
              <a href="<?php   echo $this->url('scn-social-auth-user/login/provider', array('provider' => 'google'));?>">
                <img src="/images/button-google.jpg" alt="" />
              </a>

            </div>
            <div class="poster-content float-left"><p><small><b>By signing in you agree to our <a href="https://jimmydata.com/terms-and-conditions/" title="Terms & Conditions">Terms & Conditions</b></a></small></div>
        </div>
        
    </div>
</div>

<div class="layout float-left">
  <div class="poster-blank float-left">&nbsp;</div>
</div>