
    <?php  if($this->agencies):?>
        <table cellpadding="0" cellspacing="0" border="0" class="table  table-hover  radius5" id="clients">
        <thead class="heads">
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Email</th>
                <th>Logo</th>
                <th>Status</th>
            </tr>
        </thead>
       
        <tbody>
         <?php foreach($this->agencies as $client): ?>
            <tr class="odd gradeX" onclick="location.href='agency/view/<?php echo $client->getId();?>'">
                <td><?php echo $client->getId();?></td>
                <td><?php echo $client->getName();?></td>
                <td><?php echo $client->getEmail();?></td>
                <td>
                <?php if(is_file("data/logos/agencies/".$user_mapper->getMeta($client->getId(),'logo-thumb'))):?>
                	<img width="20" src="/resources/logos/agencies/<?php echo $user_mapper->getMeta($client->getId(),'logo-thumb');?>"  /></td>
                <?php else:?>
                	<img width="20" src="/images/no-image.png"  /></td>
                <?php endif;?>
                <td><?php echo $client->getState()?'Active':'Inactive';?></td>
            </tr>
         <?php endforeach;?>
         </tbody>
        </table>  
        
        <script>
			$(document).ready(function() {
				$('#agencies').dataTable({"bLengthChange": false});
			});
        </script>       
     <?php endif; ?>  
