<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'mailchimp' => array($vendorDir . '/aaron4m/zf2-mailchimp/src'),
    'ZfcUser' => array($vendorDir . '/zf-commons/zfc-user/src'),
    'ZfcBase' => array($vendorDir . '/zf-commons/zfc-base/src'),
    'Zend\\' => array($vendorDir . '/zendframework/zendframework/library'),
    'ZendXml' => array($vendorDir . '/zendframework/zendxml/library'),
    'ScnSocialAuthTest' => array($vendorDir . '/socalnick/scn-social-auth/test'),
    'ScnSocialAuth' => array($vendorDir . '/socalnick/scn-social-auth/src'),
    'Hybrid' => array($vendorDir . '/hybridauth/hybridauth/hybridauth'),
    'BjyAuthorize\\' => array($vendorDir . '/bjyoungblood/bjy-authorize/src'),
);
