<div class="layout float-left">
 
  <div class="poster">
      <p>To get started with your referral package of JimmyData, just sign in with Google! No credit card required!</p>
    </div>
</div>

<div class="layout float-left">
  <div class="poster-white float-left">
      <div class="poster-white-inner">
          <div class="logo-button float-left"><a href="#"><img src="/images/logo3.jpg" alt="" /></a></div>
            <div class="google-button float-left">
              
              <a href="<?php   echo $this->url('scn-social-auth-user/login/provider', array('provider' => 'google'));?>">
                <img src="/images/button-google.jpg" alt="" />
              </a>

            </div>
            <div class="poster-content float-left"><p>In the  referral package you can set up few reporting templates but if you feel you need more, simply upgrade your account within the accounts tab.</p></div>
            <div class="poster-content float-left"><p><small><b>By signing in you agree to our <a href="https://jimmydata.com/terms-and-conditions/" title="Terms & Conditions">Terms & Conditions</b></a></small></div>
        </div>
        
    </div>
</div>

<div class="layout float-left">
  <div class="poster-blank float-left">&nbsp;</div>
</div>